name: gslam
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - faiss-gpu=1.6.5
  - cuda-toolkit=12.1
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - torchvision=0.16.2
  - scipy=1.11.4
  - pip
  - pip:
      - open3d==0.18.0
      - wandb
      - trimesh
      - pytorch_msssim
      - torchmetrics
      - tqdm
      - imageio
      - opencv-python
      - plyfile
      - git+https://github.com/eriksandstroem/evaluate_3d_reconstruction_lib.git@9b3cc08be5440db9c375cc21e3bd65bb4a337db7
      - git+https://github.com/JoachimRnd/simple-knn-Gaussian-SLAM.git@2c8773c664b746e44bca5dc1d5064d737b1bfc87
      - git+https://github.com/VladimirYugay/gaussian_rasterizer.git@9c40173fcc8d9b16778a1a8040295bc2f9ebf129
